Repository entando/pda-core-engine, pull requests merged in 2020-03, with the labels that each got.

#37 PDA-78 and PDA-147: Task lifecycle operations / bulk actions
  src/main/java/org/entando/plugins/pda/core/engine/Engine.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskLifecycleBulkService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskLifecycleService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskService.java
  src/main/java/org/entando/plugins/pda/core/service/task/response/TaskBulkActionResponse.java
  src/test/java/org/entando/plugins/pda/core/engine/FakeEngine.java
  src/test/java/org/entando/plugins/pda/core/engine/FakeEngineTest.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskLifecycleBulkService.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskLifecycleBulkServiceTest.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskLifecycleService.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskLifecycleServiceTest.java
Labels: approved, size/L

#40 PDA-164 Connection Format
  src/main/java/org/entando/plugins/pda/core/engine/Connection.java
  src/test/java/org/entando/plugins/pda/core/engine/ConnectionTest.java
  src/test/java/org/entando/plugins/pda/core/utils/TestUtils.java
Labels: approved, size/M

#39 PDA-112 Testing JX integration
  README.md
Labels: size/S

#41 PDA-98: Add javadoc to main classes/interfaces
  src/main/java/org/entando/plugins/pda/core/engine/Connection.java
  src/main/java/org/entando/plugins/pda/core/engine/Engine.java
  src/main/java/org/entando/plugins/pda/core/exception/EngineNotSupportedException.java
  src/main/java/org/entando/plugins/pda/core/service/group/GroupService.java
  src/main/java/org/entando/plugins/pda/core/service/process/ProcessFormService.java
  src/main/java/org/entando/plugins/pda/core/service/process/ProcessService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskAttachmentService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskCommentService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskDefinitionService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskFormService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskLifecycleBulkService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskLifecycleService.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskService.java
Labels: approved, do-not-merge/work-in-progress, size/L

#42 PDA-171 Fixed task attachment download filename
  src/main/java/org/entando/plugins/pda/core/model/File.java
  src/main/java/org/entando/plugins/pda/core/service/task/TaskAttachmentService.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskAttachmentService.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskAttachmentServiceTest.java
  src/test/java/org/entando/plugins/pda/core/service/task/FakeTaskServiceTest.java
  src/test/java/org/entando/plugins/pda/core/utils/TestUtils.java
Labels: approved, size/M
